from flask import Blueprint, send_from_directory

from app.controllers import background_job_controller, backlink_blog_controller, backlink_controller, blog_controller, blog_rework_controller, brand_controller, brand_medium_controller, checklist_controller, dashboard_controller, image_controller, news_controller, page_controller, posting_planner_controller, settings_controller, social_media_controller, tier2_blog_controller, tool_controller, weekly_planner_controller
from app.views import generation_events_view
from app.services.image_service import UPLOAD_ROOT


web = Blueprint("web", __name__)


web.add_url_rule("/dashboard", view_func=dashboard_controller.dashboard, methods=["GET"])
web.add_url_rule("/website-checklist-dashboard", view_func=checklist_controller.website_checklist_dashboard, methods=["GET", "POST"])
web.add_url_rule("/website-index-dashboard", view_func=tool_controller.website_index_dashboard, methods=["GET", "POST"])
web.add_url_rule("/website-pages", view_func=tool_controller.website_pages, methods=["GET", "POST"])
web.add_url_rule("/website-pages/download.csv", view_func=tool_controller.download_website_pages_csv, methods=["GET"])
web.add_url_rule("/website-planner", view_func=tool_controller.website_planner, methods=["GET", "POST"])
web.add_url_rule("/website-planner-v2", view_func=tool_controller.website_planner_v2, methods=["GET", "POST"])
web.add_url_rule("/website-planner/download-report", view_func=tool_controller.download_website_planner_report, methods=["POST"])
web.add_url_rule("/website-planner-v2/download-report", view_func=tool_controller.download_website_planner_v2_report, methods=["POST"])
web.add_url_rule("/website-planner-v2/download-detailed-report", view_func=tool_controller.download_website_planner_v2_detailed_report, methods=["POST"])
web.add_url_rule("/posting-planner", view_func=posting_planner_controller.posting_planner, methods=["GET", "POST"])
web.add_url_rule("/weekly-planner", view_func=weekly_planner_controller.weekly_planner, methods=["GET"])
web.add_url_rule("/brand-medium-table", view_func=brand_medium_controller.brand_medium_table, methods=["GET", "POST"])
web.add_url_rule("/generation-history", view_func=dashboard_controller.generation_history, methods=["GET"])
web.add_url_rule("/generation-history/<int:history_id>", view_func=dashboard_controller.generation_history_detail, methods=["GET", "POST"])
web.add_url_rule("/generation-history/<int:history_id>/edit", view_func=dashboard_controller.edit_generation_history, methods=["GET"])
web.add_url_rule("/generation-history/<int:history_id>/mark-draft", view_func=dashboard_controller.mark_generation_history_as_draft, methods=["POST"])
web.add_url_rule("/generation-history/<int:history_id>/delete", view_func=dashboard_controller.delete_generation_history, methods=["POST"])
web.add_url_rule("/context-planner", view_func=tool_controller.context_planner, methods=["GET", "POST"])
web.add_url_rule("/", view_func=blog_controller.index, methods=["GET", "POST"])
web.add_url_rule("/blog-rework-generator", view_func=blog_rework_controller.blog_rework_generator, methods=["GET", "POST"])
web.add_url_rule("/news-generator", view_func=news_controller.news_generator, methods=["GET", "POST"])
web.add_url_rule("/medium-blog-generator", view_func=backlink_blog_controller.backlink_blog_generator, methods=["GET", "POST"])
web.add_url_rule("/backlink-blog-generator", view_func=backlink_blog_controller.backlink_blog_generator, methods=["GET", "POST"])
web.add_url_rule("/tier-2-blog-generator", view_func=tier2_blog_controller.tier2_blog_generator, methods=["GET", "POST"])
web.add_url_rule("/tier2-blog-generator", view_func=tier2_blog_controller.tier2_blog_generator, methods=["GET", "POST"])
web.add_url_rule("/page-generator", view_func=page_controller.page_generator, methods=["GET", "POST"])
web.add_url_rule("/simple-page-generator", view_func=page_controller.simple_page_generator, methods=["GET", "POST"])
web.add_url_rule("/meta-generator", view_func=tool_controller.meta_generator, methods=["GET", "POST"])
web.add_url_rule("/gsc-planner", view_func=tool_controller.gsc_planner, methods=["GET", "POST"])
web.add_url_rule("/gsc-planner/download-summary", view_func=tool_controller.download_gsc_summary_report, methods=["POST"])
web.add_url_rule("/keyword-suggestions", view_func=tool_controller.keyword_suggestions, methods=["GET", "POST"])
web.add_url_rule("/text-tools", view_func=tool_controller.text_tools, methods=["GET"])
web.add_url_rule("/website-banned-word-checker", view_func=tool_controller.website_banned_word_checker, methods=["GET", "POST"])
web.add_url_rule("/test-page", view_func=tool_controller.test_page, methods=["GET", "POST"])
web.add_url_rule("/seo-checker", view_func=tool_controller.seo_checker, methods=["GET", "POST"])
web.add_url_rule("/seo-checker-v2", view_func=tool_controller.seo_checker_v2, methods=["GET", "POST"])
web.add_url_rule("/seo-checker/download-report", view_func=tool_controller.download_seo_checker_report, methods=["POST"])
web.add_url_rule("/indexnow", view_func=tool_controller.indexnow, methods=["GET", "POST"])
web.add_url_rule("/website-index", view_func=tool_controller.indexnow, methods=["GET", "POST"])
web.add_url_rule("/image-tools", view_func=image_controller.image_tools, methods=["GET", "POST"])
web.add_url_rule("/bulk-image-downloader", view_func=image_controller.bulk_image_downloader, methods=["GET", "POST"])
web.add_url_rule("/image-bank", view_func=image_controller.image_bank, methods=["GET"])
web.add_url_rule("/folder-image-optimizer", view_func=image_controller.folder_image_optimizer, methods=["GET", "POST"])
web.add_url_rule("/folder-image-optimizer/download/<run_id>", view_func=image_controller.download_folder_image_optimizer_zip, methods=["GET"])
web.add_url_rule("/brands", view_func=brand_controller.brands, methods=["GET", "POST"])
web.add_url_rule("/social-scheduler", view_func=social_media_controller.social_scheduler, methods=["GET", "POST"])
web.add_url_rule("/generated-social-post", view_func=social_media_controller.generated_social_post, methods=["GET", "POST"])
web.add_url_rule("/bio-generator", view_func=social_media_controller.bio_generator, methods=["GET", "POST"])
web.add_url_rule("/neutral-blog-generator", view_func=social_media_controller.neutral_blog_generator, methods=["GET", "POST"])
web.add_url_rule("/mediums", view_func=backlink_controller.backlinks, methods=["GET", "POST"])
web.add_url_rule("/backlinks", view_func=backlink_controller.backlinks, methods=["GET", "POST"])
web.add_url_rule("/settings", view_func=settings_controller.settings, methods=["GET", "POST"])
web.add_url_rule("/checklists", view_func=checklist_controller.checklist_manager, methods=["GET", "POST"])
web.add_url_rule("/banned-words", view_func=settings_controller.banned_words, methods=["GET", "POST"])
web.add_url_rule("/find-replace-settings", view_func=settings_controller.find_replace_settings, methods=["GET", "POST"])
web.add_url_rule("/preview", view_func=tool_controller.preview, methods=["POST"])
web.add_url_rule("/download_doc", view_func=tool_controller.download_doc, methods=["POST"])
web.add_url_rule("/generation-status/<token>", view_func=generation_events_view.generation_status, methods=["GET"])
web.add_url_rule("/generation-status/<token>/cancel", view_func=generation_events_view.cancel_generation_status, methods=["POST"])
web.add_url_rule("/events/generation/<token>", view_func=generation_events_view.generation_events, methods=["GET"])
web.add_url_rule("/background-jobs", view_func=background_job_controller.create_background_job, methods=["POST"])
web.add_url_rule("/background-jobs-dashboard", view_func=background_job_controller.background_jobs_dashboard, methods=["GET"])
web.add_url_rule("/background-jobs-dashboard/data", view_func=background_job_controller.background_jobs_dashboard_data, methods=["GET"])
web.add_url_rule("/background-jobs/<job_id>", view_func=background_job_controller.background_job_status, methods=["GET"])


@web.get("/uploads/<path:filename>")
def uploaded_file(filename):
    return send_from_directory(UPLOAD_ROOT, filename)
